data:
  data_path: "data/train.csv"
  test_size: 0.2
  label_column: "y"

model:
  model_save_path: "models/trained_model.pkl"
  model_params:
    max_iter: 1000
  random_state: 1337

features:
  numeric: ["x1", "x2", "x4", "x5"]
  categorical: ["x3", "x6", "x7"]
