name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Lint with flake8
        run: flake8 train scoring_service --max-line-length=100

      - name: Run pytest for specific subfolders
        run: |
          pytest tests/train
          pytest tests/service

      - name: Build image
        if: github.event_name != 'pull_request'
        run: |
          docker build --build-arg MODEL_PATH=models/trained_model.pkl -t scoring_service .
          docker tag scoring_service:latest scoring_service:${{ github.sha }}
        env:
          MODEL_PATH: models/trained_model.pkl

      - name: Run Docker container
        run: docker run -p 8000:8000 scoring

      - name: Wait for application to be ready
        run: |
          for i in {1..10}; do
            curl -f http://localhost:8000/score/ && break || echo "Waiting for application to start..."
            sleep 3
          done

      - name: Run integration tests
        run: |
          pytest tests/integration
